global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "node_exporter"
    scheme: https
    static_configs:
      - targets: ["node.pki.vagrant:9100"]
    tls_config:
      cert_file: /etc/prometheus/ssl/node.pki.vagrant.cert
      key_file: /etc/prometheus/ssl/node.pki.vagrant.key
      ca_file: /etc/prometheus/ssl/ca.cert
