global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093
scrape_configs:
  - job_name: "alertmanager"
    static_configs:
      - targets: ["localhost:9093"]
  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:3000"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    bearer_token: "insert.here"
    static_configs:
      - targets: ["localhost:8200"]